# Generated by Django 2.0.9 on 2018-12-13 13:04

import blog.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serie', models.CharField(choices=[('Nar', 'Naruto'), ('Dgb', 'Dragon Ball'), ('DeN', 'Death Note'), ('Opm', 'One Punch Man')], max_length=3)),
                ('fecha_subida', models.DateTimeField(default=django.utils.timezone.now)),
                ('imagen', models.ImageField(blank=True, null=True, upload_to=blog.models.get_image_path)),
                ('frase', models.TextField()),
                ('nombre_personaje', models.CharField(choices=[('Naruto', 'Naruto'), ('Saitama', 'Saitama')], max_length=50)),
                ('autor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
